# Generated by Django 2.1.2 on 2019-05-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otec',
            name='correo',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colegio',
            name='correo',
            field=models.CharField(max_length=70),
        ),
    ]
