# Generated by Django 2.2.dev20180704171535 on 2019-05-17 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190514_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('hora', models.CharField(max_length=70)),
                ('direccion', models.CharField(max_length=100)),
                ('otec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Otec')),
            ],
        ),
    ]
