# Generated by Django 2.1.2 on 2019-05-31 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typedocument',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
