# Generated by Django 2.1.2 on 2019-06-03 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20190530_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='archivo',
            field=models.FileField(default='null', upload_to='material/'),
            preserve_default=False,
        ),
    ]
