# Generated by Django 2.2.dev20180625180104 on 2019-06-05 15:31

from django.db import migrations, models
import material.models
import material.validators


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_auto_20190602_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=material.models.upload_location, validators=[material.validators.valid_extension]),
        ),
    ]
